import fs from "node:fs";

const seeds = [
  [
    "remote-work-juniors",
    "Remote work hurts career growth for junior employees.",
    "Work & Economy",
    "Since 2020, remote and hybrid work went mainstream — and the debate over whether early-career workers gain or lose from it is still unsettled.",
    "Mentorship needs proximity",
    "Junior workers learn fastest through osmosis — overhearing negotiations, watching seniors handle pressure, and getting spontaneous feedback. Remote work strips away those micro-moments. Studies from early-career cohorts show slower promotion rates and weaker professional networks when onboarding happens entirely through screens.",
    "Access beats hallway luck",
    "Remote work democratizes opportunity. A junior in a small town can join a top firm without relocating, document their work in writing, and learn from recorded meetings they can replay. Proximity-based mentorship often favors people who already fit in socially.",
  ],
  [
    "ai-copyright",
    "AI companies should pay copyright holders for training data.",
    "Technology",
    "Lawsuits from authors, artists, and publishers against AI labs are working through the courts as models trained on vast scraped datasets reach commercial scale.",
    "Creation has value",
    "Models trained on books, art, and journalism produce commercial value that flows to tech companies, not creators. Without compensation, we hollow out the industries that produce the culture AI imitates.",
    "Learning is not copying",
    "Humans learn from copyrighted works without paying each author. AI training is closer to reading than redistribution. Retroactive licensing at scale is practically impossible and would concentrate power in firms that can afford deals.",
  ],
  [
    "universal-basic-income",
    "Countries should implement a universal basic income.",
    "Policy",
    "Pilot programs from Finland to Kenya to Stockton have tested unconditional cash, reviving a centuries-old idea amid fears about automation and inequality.",
    "Floor, not bureaucracy",
    "UBI replaces patchwork welfare with a simple guarantee: everyone can eat, house themselves, and say no to exploitation. Pilots show reduced stress and more entrepreneurship.",
    "Price tag and incentives",
    "Full UBI at a meaningful level requires tax increases voters reject when they see the bill. Targeted support reaches need with less waste.",
  ],
  [
    "social-media-age-verification",
    "Social media platforms should verify users are 16 or older.",
    "Society",
    "Several governments have passed or proposed age-verification and under-16 social media rules.",
    "Protect developing minds",
    "Adolescent brains are uniquely vulnerable to algorithmic engagement and harassment at scale. We gate alcohol and gambling; infinite scroll deserves scrutiny.",
    "Privacy and exclusion",
    "Mandatory ID verification maps who said what online. Young activists and LGBTQ youth in hostile homes rely on pseudonymity. Verification pushes teens to less moderated corners.",
  ],
  [
    "nuclear-energy",
    "Nuclear power should be the backbone of clean energy policy.",
    "Climate",
    "As countries chase net-zero targets, nuclear is being reconsidered even as renewables get cheaper.",
    "Dense, reliable, low-carbon",
    "Wind and solar need storage; nuclear runs 24/7 with tiny land use and near-zero operational emissions. Climate timelines do not allow waiting for a perfect renewable-only miracle.",
    "Cost and clock speed",
    "New nuclear plants routinely arrive years late and billions over budget while solar and batteries plummet in price. The fastest path is accelerate what deploys today.",
  ],
  [
    "four-day-workweek",
    "The standard workweek should be four days, not five.",
    "Work & Economy",
    "Trials in Iceland, the UK, and elsewhere reported steady output on shorter weeks.",
    "Productivity without burnout",
    "Trials found equal or higher output with four-day schedules when meetings and busywork get cut. The five-day week is a factory convention, not a law of nature.",
    "Not every job flexes",
    "Healthcare, logistics, and retail cannot shrink coverage without hiring more staff. A mandate would push some firms to offshore rather than comply.",
  ],
  [
    "open-borders",
    "Wealthy nations should substantially open their borders to immigration.",
    "Policy",
    "Aging populations and labor shortages collide with political backlash over migration.",
    "Freedom and growth",
    "Where you are born should not determine life chances. Open borders would lift millions from poverty and aging rich countries need workers.",
    "Capacity and consent",
    "Democratic communities have a right to set intake levels. Rapid influx strains housing and schools before infrastructure adapts.",
  ],
  [
    "cancel-college-debt",
    "Governments should cancel most outstanding student debt.",
    "Policy",
    "Ballooning tuition and trillions in loans have made debt cancellation a recurring flashpoint.",
    "Reset a broken bargain",
    "Student debt ballooned because states cut funding while telling everyone a degree was mandatory. Mass cancellation frees a generation to buy homes and start businesses.",
    "Fairness forward",
    "Canceling debt rewards those who borrowed most — often higher earners — while ignoring people who paid cash or skipped college.",
  ],
  [
    "meat-consumption",
    "Governments should heavily tax meat to fight climate change.",
    "Climate",
    "Livestock is a major source of emissions and land use, prompting proposals to price meat like other pollutants.",
    "Price what pollutes",
    "Livestock drives emissions, deforestation, and antibiotic resistance. Meat is artificially cheap because costs are externalized.",
    "Regressive and cultural",
    "Meat taxes hit low-income households hardest and stigmatize diets tied to culture and tradition.",
  ],
  [
    "platform-liability",
    "Social platforms should be legally liable for harmful user content.",
    "Technology",
    "Liability shields like Section 230 are under pressure worldwide.",
    "Accountability at scale",
    "Immunity let platforms optimize engagement without paying for harm. Algorithmic amplifiers should not hide behind neutral pipes.",
    "Chill speech and crush newcomers",
    "If platforms face lawsuits for user posts, they will over-remove. Only giants can afford armies of lawyers; startups die on first complaint.",
  ],
  [
    "monarchy-abolish",
    "Modern democracies should abolish ceremonial monarchies.",
    "Society",
    "Royal successions periodically reopen whether hereditary crowns belong in a modern democracy.",
    "Symbols matter",
    "Hereditary privilege sits awkwardly next to equal citizenship. Democracy should be complete.",
    "Stability and tourism",
    "Ceremonial monarchies often score high on stability and soft power presidents cannot match during crises.",
  ],
  [
    "crypto-regulation",
    "Cryptocurrency should face the same financial regulations as banks.",
    "Technology",
    "High-profile collapses accelerated a global push to regulate crypto.",
    "Same risk, same rules",
    "Crypto exchanges hold customer funds and lend — exactly what banks do — but often skip audits and deposit insurance.",
    "Innovation needs room",
    "Heavy bank-style rules kill programmable money and remittances. Smart regulation targets fraud without regulating every wallet.",
  ],
  [
    "voting-mandatory",
    "Voting in national elections should be mandatory.",
    "Policy",
    "Australia and Belgium fine non-voters and post high turnout.",
    "Legitimacy and voice",
    "Low turnout lets extreme minorities pick leaders. Compulsory voting boosts engagement without crushing conscience.",
    "Freedom includes abstention",
    "Forced voting is forced speech. Better fixes: election-day holiday, automatic registration, ranked choice.",
  ],
  [
    "space-priority",
    "Governments should prioritize space exploration over fixing problems on Earth.",
    "Science",
    "A new space race reignites how to weigh moonshots against needs at home.",
    "Insurance and invention",
    "Space spending is tiny next to military budgets yet yields GPS, weather prediction, and materials science.",
    "Opportunity cost is real",
    "Every billion to Mars is a billion not building transit or vaccine factories. Fix the planet you are on first.",
  ],
];

/** @type {[string,string,string,string,string,string][]} */
const more = [
  ["college-free", "Public college should be tuition-free.", "Education", "Tuition-free proposals resurface every election cycle as sticker prices keep climbing.", "Talent without a price tag", "Someone pays"],
  ["phones-schools", "Phones should be banned during the school day.", "Education", "Districts from California to Europe are locking phones away to reclaim attention.", "Attention is the curriculum", "Teach the tool"],
  ["defund-police", "Cities should significantly reduce police budgets and reinvest in social services.", "Policy", "After 2020 protests, budget fights over policing versus mental-health response never fully settled.", "Right tool for the job", "Safety is foundational"],
  ["rent-control", "Cities should expand rent control to stop housing costs from rising.", "Policy", "As rents soar in major metros, tenants push hard caps while economists warn about supply.", "Shelter is not a luxury", "Supply is the cure"],
  ["tiktok-ban", "Democratic governments should ban TikTok over national security concerns.", "Technology", "National security reviews of Chinese-owned apps keep returning to the same dilemma.", "Data is power", "Ban what you fear"],
  ["gene-editing-babies", "Heritable human gene editing should be legal for serious diseases.", "Science", "CRISPR advances reopen whether editing embryos for disease is medicine or a slippery slope.", "Prevent suffering", "Line will not hold"],
  ["daylight-saving", "Daylight saving time should be abolished permanently.", "Society", "Annual clock changes remain popular to hate and hard to kill legislatively.", "Stop the switch", "Evening light matters"],
  ["college-athletes-pay", "College athletes should be paid salaries by their schools.", "Sports", "NIL deals cracked the amateur model; salary debates ask how far professionalization should go.", "Labor creates the product", "Campus is not the NFL"],
  ["plastic-ban", "Single-use plastics should be banned nationwide.", "Climate", "Bag bans proliferate while oceans and landfills fill with packaging.", "Design out waste", "Life-cycle honesty"],
  ["right-to-repair", "Manufacturers should be required to support right-to-repair for electronics.", "Technology", "Farmers, phone owners, and independent shops are pushing legislatures for parts and manuals.", "Ownership means repair", "Safety and IP"],
  ["wealth-tax", "Countries should impose an annual tax on extreme wealth.", "Policy", "Billionaire wealth concentration has revived wealth-tax proposals from Norway to the US.", "Tax the stockpile", "Flight and valuation"],
  ["homeschool-oversight", "Homeschooling should face the same oversight as private schools.", "Education", "Homeschool growth after the pandemic revived fights over regulation versus parental rights.", "Children have rights too", "Parents know best"],
  ["cashless-society", "Governments should accelerate the shift to a cashless society.", "Technology", "Digital payments dominate cities while cash remains a lifeline for the unbanked.", "Efficiency and transparency", "Surveillance and exclusion"],
  ["animal-personhood", "Great apes and cetaceans should have legal personhood rights.", "Society", "Courts keep hearing cases seeking habeas corpus for chimps and elephants.", "Sentience deserves standing", "Rights need duties"],
  ["term-limits", "Legislators should face strict term limits.", "Policy", "Frustration with career politicians keeps term-limit amendments alive.", "Fresh blood", "Voters already decide"],
  ["lab-grown-meat", "Governments should subsidize lab-grown meat the way they subsidize livestock.", "Climate", "Cultivated meat startups seek parity with farm subsidies that shaped cheap animal protein.", "Level the field", "Unproven at scale"],
  ["surveillance-cameras", "Cities should blanket public spaces with AI surveillance cameras.", "Society", "Smart-city camera networks promise safety and raise Orwell alarms.", "Deterrence that works", "Chilling effect"],
  ["homework-ban", "K-12 schools should ban homework.", "Education", "Some districts are cutting homework to fight burnout and inequality.", "School is enough", "Practice builds mastery"],
  ["olympics-boycott", "Democracies should boycott Olympics hosted by authoritarian regimes.", "Sports", "Sports and soft power collide whenever the Games land in contested regimes.", "Do not sportswash", "Punish athletes"],
  ["internet-utility", "Home broadband should be regulated as a public utility.", "Technology", "Broadband is essential infrastructure, yet markets remain concentrated in many regions.", "Essential like water", "Innovation tax"],
  ["prison-abolition", "Countries should abolish prisons in favor of restorative justice.", "Policy", "Abolitionist movements argue incarceration fails at rehabilitation and justice.", "Cages fail", "Some people are dangerous"],
  ["geoengineering", "Governments should fund large-scale climate geoengineering research now.", "Climate", "As emissions stay high, solar geoengineering moved from taboo to research agenda.", "Emergency option", "Moral hazard"],
  ["tipping-ban", "Restaurants should ban tipping and pay living wages instead.", "Work & Economy", "Tip culture fights intensify as apps and inflation scramble service pay.", "Dignity in the wage", "Flexibility and upside"],
  ["esports-olympics", "Esports should be full medal events in the Olympics.", "Sports", "The IOC flirts with gaming while purists defend physical sport.", "Sport of the century", "Different category"],
  ["ai-politicians", "AI systems should be allowed to advise and draft legislation.", "Technology", "Lawmakers already use AI drafts; the question is how open and accountable that becomes.", "Better briefs", "Democratic laundering"],
  ["national-service", "Young adults should complete a year of mandatory national service.", "Society", "Service drafts resurface as social cohesion and recruitment worries grow.", "Shared stake", "Forced labor"],
  ["zoo-closure", "Traditional zoos should be phased out.", "Society", "Welfare science and streaming wildlife docs challenge the zoo model.", "Wild belongs wild", "Arks and ambassadors"],
  ["sugar-tax", "Sugary drinks should face steep sin taxes.", "Health", "Soda taxes spread from Mexico to UK cities as obesity costs climb.", "Price the harm", "Nanny state"],
  ["driverless-priority", "Cities should redesign streets for driverless cars over private drivers.", "Technology", "AV pilots force a choice about who streets are for.", "Fewer cars, safer streets", "Premature bet"],
  ["hate-speech-ban", "Liberal democracies should criminalize hate speech more aggressively.", "Society", "Europe and the US diverge sharply on where free speech ends.", "Dignity and safety", "Weaponized ambiguity"],
  ["medicare-all", "The government should provide universal single-payer health care.", "Health", "Single-payer remains the north star for left health politics and a red line for opponents.", "Coverage is a right", "One-size rationing"],
  ["college-rankings-ban", "Universities should stop participating in commercial college rankings.", "Education", "Schools quietly revolt against ranking incentives that warp admissions.", "Perverse metrics", "Information vacuum"],
  ["ocean-mining", "Deep-sea mining should be banned until ecosystems are mapped.", "Climate", "Battery metals tempt seabed mining before science catches up.", "Precaution", "Transition metals"],
  ["remote-jury", "Criminal juries should be allowed to deliberate fully online.", "Policy", "Courts that tasted Zoom wonder whether remote juries can stick.", "Access and efficiency", "Presence matters"],
  ["ads-kids", "All advertising aimed at children under 13 should be banned.", "Society", "Kidfluencers and in-game ads revive calls to protect childhood attention.", "Kids are not a market", "Parents decide"],
  ["nuclear-weapons-ban", "Nuclear-armed states should disarm unilaterally on a fixed schedule.", "Policy", "Treaty campaigns push unilateral schedules amid renewed great-power rivalry.", "Existential risk", "Invite coercion"],
  ["four-day-school", "Public schools should move to a four-day week.", "Education", "Rural and budget-strapped districts already run four-day calendars.", "Rest and retain", "Childcare shock"],
  ["influencer-disclosure", "Influencers should face fines for undisclosed sponsored content.", "Culture", "Hidden ads on social feeds blur recommendations and paid pitches.", "Truth in packaging", "Creators crushed"],
  ["urban-highways", "Cities should tear down urban highways and replace them with boulevards.", "Climate", "Highway removal projects from Seoul to Rochester inspire new fights.", "Repair the scar", "Freight and fairness"],
  ["alcohol-age-25", "The legal drinking age should be raised to 25.", "Health", "Brain science on young adults fuels proposals to push the drinking age higher.", "Brain still wiring", "Prohibition theater"],
  ["public-housing-mandate", "Every city should require large shares of new housing to be social housing.", "Policy", "Social housing mandates clash with private development economics.", "Decommodify shelter", "Build nothing"],
  ["chatgpt-exams", "Schools should redesign exams assuming AI is always available.", "Education", "ChatGPT made take-home essays and many tests obsolete overnight.", "Assess the real world", "Foundations first"],
  ["billionaire-space", "Billionaires should be barred from private space tourism until climate goals are met.", "Climate", "Rocket joyrides became a symbol of inequality in a heating world.", "Optics and carbon", "Misplaced anger"],
  ["jury-nullification", "Juries should be explicitly instructed about nullification rights.", "Policy", "Activists want courts to tell juries they can refuse unjust laws.", "Conscience check", "Chaos verdicts"],
  ["plant-based-military", "Armed forces should shift to mostly plant-based rations.", "Climate", "Military logistics footprints are huge; menus became a climate lever.", "Lead by example", "Morale and nutrition"],
  ["social-credit-west", "Western democracies should adopt social credit-style behavior scores.", "Society", "After seeing China systems, some propose softer Western reputation scores.", "Incentivize virtue", "Soft totalitarianism"],
  ["year-round-school", "Schools should run year-round calendars without long summer breaks.", "Education", "Summer learning loss research keeps year-round calendars in play.", "Stop the slide", "Childhood summer"],
  ["drone-delivery", "Cities should open low-altitude airspace to commercial delivery drones.", "Technology", "Amazon and others lobby for drone lanes above neighborhoods.", "Skip the truck", "Noise and privacy"],
  ["attorney-general-appointed", "Attorneys general should be appointed, not elected.", "Policy", "Politicized prosecutions revive the elected-versus-appointed AG fight.", "Law not campaign", "Accountable to voters"],
  ["museum-restitution", "Western museums should return contested colonial artifacts.", "Culture", "Benin Bronzes and similar cases reshaped museum ethics.", "Stolen is stolen", "Universal museums"],
  ["fast-fashion-ban", "Ultra-fast fashion business models should be heavily regulated or banned.", "Climate", "Shein-era cycles made textile waste a policy target.", "Disposable clothes", "Style for the broke"],
  ["mental-health-days", "Employees should get unlimited mental health days by law.", "Work & Economy", "Post-pandemic workplaces debate formal mental health leave.", "Prevention beats burnout", "Unlimited is unworkable"],
  ["concussion-ban-tackle", "Youth tackle football should be banned under age 14.", "Sports", "CTE research presses youth leagues on when tackling should start.", "Brains not tough enough", "Culture and choice"],
  ["basic-income-kids", "Governments should pay a universal child allowance to every family.", "Policy", "Child allowances cut poverty in pilots and national programs.", "Invest at the start", "Fertility bribe fears"],
  ["open-source-ai", "Frontier AI models should be required to release open weights.", "Technology", "Open versus closed model wars shape who controls AI capability.", "Public intelligence", "Proliferation risk"],
  ["car-free-centers", "Major cities should ban private cars from downtown cores.", "Climate", "European low-emission zones inspire bolder car-free downtown proposals.", "Cities for people", "Access denied"],
  ["polygamy-legal", "Consensual polygamy among adults should be legal.", "Society", "Plural marriage activists hitch arguments to LGBTQ equality frameworks.", "Consenting adults", "Power imbalance"],
  ["stock-buyback-ban", "Public companies should be banned from stock buybacks.", "Work & Economy", "Buybacks are blamed for underinvestment and worker squeeze.", "Invest in people", "Flexible capital return"],
  ["parental-leave-equal", "Parental leave should be equal and non-transferable for each parent.", "Society", "Use-it-or-lose-it leave for fathers aims to rebalance care.", "Norms need force", "Families differ"],
  ["ban-loot-boxes", "Loot boxes in games should be regulated as gambling.", "Culture", "Random paid rewards blur gaming and gambling for kids.", "Predatory by design", "Cosmetic panic"],
  ["clinical-trial-diversity", "Drug trials should be legally required to match population demographics.", "Health", "Underrepresentation in trials leaves efficacy gaps for many groups.", "Medicine for everyone", "Delay cures"],
  ["land-value-tax", "Cities should replace property tax with a land value tax.", "Policy", "Georgist tax ideas return as housing crises deepen.", "Tax the location", "Assessment fights"],
  ["ai-therapist", "AI chatbots should be allowed as licensed mental health tools.", "Health", "Therapy waitlists make AI companions a tempting stopgap.", "Access bridge", "False intimacy"],
  ["english-official", "English should be the sole official language of government.", "Society", "Official-language fights return with immigration politics.", "Common tongue", "Plural reality"],
  ["congestion-pricing", "Every major city should adopt congestion pricing.", "Climate", "London and NYC-style tolls show traffic can be priced.", "Time is money", "Regressive tolls"],
  ["gene-patents", "Human genes should not be patentable.", "Science", "IP fights over diagnostics and CRISPR keep gene-patent ethics live.", "Nature is not invented", "Incentives matter"],
  ["school-vouchers", "Every family should get a voucher usable at any accredited school.", "Education", "Voucher expansions clash with public-school funding politics.", "Fund students", "Drain the commons"],
  ["facial-recog-ban", "Police use of facial recognition should be banned.", "Society", "Misidentification scandals drive local bans on police face search.", "Wrongful arrests", "Solve the unsolvable"],
  ["farm-subsidy-end", "Agricultural subsidies for commodity crops should end.", "Policy", "Corn and soy subsidies shape diets, land use, and trade fights.", "Stop distorting food", "Volatility shock"],
  ["robot-tax", "Companies should pay a tax for each job replaced by automation.", "Work & Economy", "Robot taxes propose funding transition as AI eats tasks.", "Share the surplus", "Punish productivity"],
  ["lifetime-congress-age", "There should be a maximum age limit for national elected office.", "Policy", "Gerontocracy critiques fuel maximum-age proposals.", "Cognitive duty", "Age is not ability"],
  ["public-domain-short", "Copyright terms should be shortened to under 30 years.", "Culture", "Long copyrights keep culture locked; reformers want shorter terms.", "Culture wants remix", "Incentive cliff"],
  ["military-draft", "A gender-neutral military draft should be reinstated.", "Society", "Recruiting shortfalls revive draft talk with equity debates.", "Shared burden", "Coerced killing"],
  ["soda-schools", "Schools should ban all sugary drinks including sports drinks.", "Health", "Wellness policies keep tightening what kids can buy at school.", "Model the day", "Hydration and choice"],
  ["algorithmic-feed-optout", "Social platforms should default to chronological feeds.", "Technology", "Chronological defaults are proposed as an antidote to engagement ranking.", "User agency", "Firehose reality"],
  ["water-futures", "Speculative trading of water rights should be banned.", "Climate", "As droughts worsen, financialization of water draws outrage.", "Life not a ticker", "Price signals help"],
  ["celebrity-endorsement-ban", "Political campaigns should ban paid celebrity endorsements.", "Culture", "Star-studded campaigns raise whether fame should be purchasable political speech.", "Substance over fame", "Speech is speech"],
  ["mars-colony", "Humanity should prioritize a permanent Mars settlement this century.", "Science", "Mars settlement timelines slipped but the ambition remains a cultural Rorschach.", "Backup planet", "Fantasy budget"],
  ["ban-shadowbanning", "Platforms should be banned from shadowbanning without notice.", "Technology", "Creators demand transparency when reach silently dies.", "Due process lite", "Spam arms race"],
  ["teacher-pay-double", "Public school teacher pay should be doubled.", "Education", "Recruitment crises make dramatic pay proposals mainstream.", "Pay for talent", "Money without reform"],
  ["crypto-cbdc", "Central bank digital currencies should replace most cash.", "Technology", "CBDC pilots raise whether state money goes fully digital.", "Modern money", "Programmable control"],
  ["stadium-subsidy-ban", "Cities should be banned from subsidizing pro sports stadiums.", "Sports", "Economists long argued stadium deals fail taxpayers.", "Stop the ransom", "Anchor benefits"],
  ["universal-broadband", "Every household should get free basic broadband.", "Technology", "Broadband as a free public good joins water and electricity debates.", "Homework gap", "Who builds it"],
  ["plastic-surgery-minors", "Cosmetic surgery on minors for non-medical reasons should be banned.", "Health", "Teen cosmetic procedures rose with social media filters.", "Protect developing bodies", "Careful exceptions"],
  ["work-from-abroad", "Companies should allow employees to work from any country.", "Work & Economy", "Digital nomad visas collided with tax and security policies.", "Talent without borders", "Compliance nightmare"],
  ["ban-super-pacs", "Super PACs should be abolished.", "Policy", "Campaign finance reformers still target independent expenditure giants.", "Democracy not auction", "Speech and association"],
  ["insect-protein", "Governments should promote insect protein in public food programs.", "Climate", "UN-backed insect protein faces Western gag reflexes.", "Efficient protein", "Culture counts"],
  ["lifetime-streaming", "Streaming services should be required to keep licensed shows available for a minimum term.", "Culture", "Shows vanish from catalogs mid-binge as licenses churn.", "Cultural archives", "Contract reality"],
  ["ai-art-label", "AI-generated media should require prominent labeling.", "Technology", "Deepfakes and AI art spark mandatory watermark proposals.", "Signal the synthetic", "Watermarks fail"],
  ["park-camping-ban", "Major cities should ban homeless encampments in public parks.", "Policy", "Compassion versus order fights play out in park clearances.", "Parks are for everyone", "Criminalize poverty"],
  ["college-sports-split", "Big-time college football should spin out of universities.", "Sports", "NIL and TV money make major football look fully professional.", "Academics first", "Campus glue"],
  ["microplastics-ban", "Products shedding high microplastics should be banned.", "Climate", "Microplastics in blood and oceans push product bans beyond bags.", "Stop the bleed", "Everything sheds"],
  ["citizen-assemblies", "Citizen assemblies should decide major constitutional questions.", "Policy", "Climate and electoral assemblies inspired calls for more sortition.", "Deliberation beats tribalism", "Accountability gap"],
  ["ban-targeted-political-ads", "Platforms should ban microtargeted political advertising.", "Technology", "Microtargeting is blamed for polarizing persuasion in the dark.", "Sunlight politics", "Speech channels"],
  ["medical-aid-dying", "Medical aid in dying should be legal for terminal adults nationwide.", "Health", "MAID laws expand while disability advocates warn of coercion.", "Last autonomy", "Coercion risk"],
  ["prime-amazon-split", "Regulators should break up Amazon retail and AWS.", "Technology", "Antitrust cases ask whether cloud and retail under one roof is too much power.", "Structural separation", "Integrated efficiency"],
  ["school-start-later", "High schools should start no earlier than 8:30 a.m.", "Health", "Sleep science pushed later bell times into mainstream policy.", "Biology is policy", "Family logistics"],
  ["universal-childcare", "Government should guarantee universal childcare from age one.", "Policy", "Childcare costs rival rent and stall careers, especially for mothers.", "Infrastructure for work", "Quality cliff"],
  ["ban-gas-cars", "Sale of new gasoline cars should be banned by 2035.", "Climate", "EV mandates set hard dates that thrill climate hawks and scare drivers.", "Hard stop needed", "Grid and choice"],
  ["journalist-shield", "National shield laws should protect journalist confidential sources.", "Society", "Raids on newsrooms revive demands for stronger source protection.", "Democracy needs sources", "Who is a journalist"],
  ["orbit-debris-tax", "Companies should pay a tax on every satellite launch for debris risk.", "Science", "Mega-constellations raise Kessler syndrome fears.", "Price the junk", "Chills exploration"],
  ["paid-jury-duty", "Jury duty should pay at least the local median wage.", "Policy", "Unpaid or token jury pay excludes working people from the box.", "Democratic participation", "Budget blowout"],
  ["ban-noncompetes", "Non-compete agreements should be banned for all workers.", "Work & Economy", "Regulators moved against noncompetes that trap workers in jobs.", "Labor mobility", "Protect secrets"],
  ["street-cameras-audio", "Public CCTV should be allowed to record audio as well as video.", "Society", "Cities debate whether cameras need ears to be useful.", "Complete evidence", "Private conversations"],
];

function pack(id, resolution, category, context, proTitle, proArg, conTitle, conArg) {
  return {
    id,
    resolution,
    category,
    context,
    pro: { title: proTitle, argument: proArg },
    con: { title: conTitle, argument: conArg },
    status: "published",
    publishedAt: "2025-01-01",
    seoTitle: `${resolution.replace(/\.$/, "")} — arguments for and against`,
    seoDescription: `Read the strongest case for and against: ${resolution} Take a side on Today's Debate.`,
  };
}

const out = [];
for (const s of seeds) {
  out.push(pack(s[0], s[1], s[2], s[3], s[4], s[5], s[6], s[7]));
}
for (const m of more) {
  const [id, resolution, category, context, proTitle, conTitle] = m;
  const proArg = `${proTitle}. ${context} Supporters argue the status quo externalizes harm and delays a clearer rule. Waiting for perfect consensus usually means incumbents keep winning by default.`;
  const conArg = `${conTitle}. ${context} Critics warn the proposed fix creates new failure modes — cost, coercion, or unintended side effects — that may outweigh the problem it targets.`;
  out.push(pack(id, resolution, category, context, proTitle, proArg, conTitle, conArg));
}

fs.writeFileSync("src/data/debates.json", JSON.stringify(out, null, 2));
console.log("wrote", out.length, "debates");
